### ISSUE TITLE
Calypso SmartCard support

### ISSUE THREAD

**Issue by mrleblanc101** [robbiet480/TransitPal#2]
Hi,
Would it be possible to support Calypso SmartCard technology ? I have no idea if it's possible but that's what most Transit company use in Canada

**Comment by tJulianB** [comment]
Used too in Paris (Navigo pass)

**Comment by robbiet480** [comment]
[This list](https://github.com/micolous/metrodroid#supported-cards--agencies) is pretty much everything that _could_ be supported by TransitPal, although support would obviously need to be added. Keep in mind, iOS supports everything on that list except MIFARE Classic.

**Comment by tJulianB** [comment]
Awesome. 

I ran the app on my iPhone Xs Max running iOS 13 Beta 5 with Xcode 11 beta 5 and I have succesfully the _ready to scan_ modal, but with my Navigo card (which is ISO 14443) I cannot get at least into `tagReaderSession` method, it's stuck as if there is no card.

PS: The same card works great on a Samsung Galaxy S8 with Metrodroid.

**Comment by phcoder** [comment]
Calypso smartcard including Navigo is supported by my iOS port of Metrodroid: https://github.com/micolous/metrodroid/pull/568
