### ISSUE TITLE
Value of type 'ReversedCollection<[Date]>' has no member 'identified'

### ISSUE THREAD

**Issue by timroesner** [robbiet480/TransitPal#3]
Trying to get your project to run with beta 5, which seems to have some breaking changes. Was able to fix some errors but got stuck on the above and couldn't find what replaced `Modal` which is used in the `CardHistoryList` 

If I get some pointers I'd be happy to make a PR when I get it running on my machine.

**Comment by robbiet480** [comment]
@timroesner Funny enough I just sat down to check this out on the latest beta a few minutes ago. Will get things fixed up and pushed shortly.

**Comment by robbiet480** [comment]
@timroesner Got it all fixed, just tracking down one last issue and then will push. ETA 10-15 minutes!

**Comment by timroesner** [comment]
Thank you so much. It's such a great feeling to scan my Clipper card on my phone. 

Found a few bugs with the transactions I have. (I.e. no ExitTimestamp) I'll do a PR for those

**Comment by robbiet480** [comment]
Awesome! If you see any data specific issues such as missing station names or operator names, those should be fixed upstream like I did [here](https://github.com/micolous/metrodroid/pull/458). Please tag me on any PRs you open on Metrodroid. Thanks!
