### ISSUE TITLE
NFC session does not detect Clipper card on iOS 13.0 GM / iPhone XS

### ISSUE THREAD

**Issue by chrisballinger** [robbiet480/TransitPal#7]
The `func tagReaderSession(_ session: NFCTagReaderSession, didDetect tags: [NFCTag])` callback is never triggered on iOS 13.0 GM running on an iPhone XS.

At first I thought it was because `readerSession` was not retained, but adding a retain didn't resolve the issue.

**Comment by robbiet480** [comment]
Did you add the relevant AIDs to the Info.plist?

**Comment by robbiet480** [comment]
(Assuming that you are trying to scan something other than Clipper that is)

**Comment by chrisballinger** [comment]
Was trying to scan a standard Clipper card. Is there any other setup required to scan those?

The card works at BART gates so it's definitely functional, but I'll try another card I have lying around as well. The phone also works regularly w/ Apple Pay, so I'm guessing the NFC hardware is okay.

**Comment by chrisballinger** [comment]
Tried again on a different Clipper card and on new hardware (iPhone 11 Pro Max). Perhaps something else changed in CoreNFC / iOS 13 SDK since the beta?
